name: tudo_server
description: Server counterpart to the tudo app
version: 1.0.0
homepage: https://github.com/cachapa/tudo_server

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  crdt_sync: ^0.0.6
#    path: ../../crdt_sync
  http: ^1.1.0
  postgres_crdt: ^1.1.1+1
#    path: ../../postgres_crdt
  rxdart: ^0.27.7
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  version: ^3.0.2

dev_dependencies:
  lints: any
  test: any
